spring:
  application:
    name: omnianalytics

  datasource:
    url: jdbc:postgresql://localhost:5432/omnidb
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
    streams:
      application-id: omni-streams-app

  data:
    redis:
      host: localhost
      port: 6379
    elasticsearch:
      uris: http://localhost:9200